### ISSUE TITLE
No regex version

### ISSUE THREAD

**Issue by eugene-eeo** [amjith/fuzzyfinder#2]
Just an FYI: it's slightly faster, but at the cost of readability :wink::

``` python
def make_searcher(query):
    if len(query) == 0:
        return lambda x: (True, 0, 0)

    head = query[0]
    tail = query[1:]

    def matcher(datum):
        running = 0
        first = datum.find(head)
        if first == -1:
            return (False, -1, -1)
        datum = datum[first+1:]

        for char in tail:
            index = datum.find(char)
            if index == -1:
                return (False, -1, -1)
            running += index
            datum = datum[index+1:]

        return (True, running, first)

    return matcher


def fuzzyfinder(query, data):
    suggestions = []
    searcher = make_searcher(query)

    for item in data:
        matched, distance, first = searcher(item)
        if not matched:
            continue
        suggestions.append((distance, first, item))
    return [x for _, _, x in sorted(suggestions)]
```

Test code:

``` python
collection = [
    'django_migrations.py',
    'django_admin_log.py',
    'main_generator.py',
    'migrations.py',
    'api_user.doc',
    'user_group.doc',
    'accounts.txt',
]
from timeit import timeit
timeit('fuzzyfinder("mig", collection)', setup='from __main__ import collection; from fuzzyfinder import fuzzyfinder')
```

|  | new | old | speedup |
| --- | --- | --- | --- |
| CPython | 11.90004337999926 | 14.990981923001527 | 20.61% |
| PyPy | 2.1479620933532715 | 3.060289144515991 | 29.64% |

**Comment by amjith** [comment]
Very nice!! That is a clever implementation. 

I'm in the middle of changing a few things and adding some features. I'm going to keep this PR open and revisit how this performs once I'm done. 

Were you using the library for a real application? I'm curious to know how this is used in the wild.

**Comment by eugene-eeo** [comment]
@amjith I plan on using it for autocompletion in a personal project, and I also found the blog post to have very systematic approach.

On the code: you should not have the `@export` decorator. Just put the function name in the `__all__` list in `__init__` module. Less magic, less headaches. Also since the module is quite short you might want to just use a file instead of a directory, see the `py_modules` option in `setup.py`.

**Comment by amjith** [comment]
The `@export` decorator is a trick I learned from David Beazly's training from PyCon 2015. 

http://pyvideo.org/video/3387/modules-and-packages-live-and-let-die

http://www.dabeaz.com/modulepackage/ModulePackage.pdf

I thought he made some valid points about it's usefulness. 

I will consider using just a file instead of a directory. I originally started this project using a cookiecutter template. In retrospect it might have been an overkill. Thank you for the suggestions. 😄

**Comment by eugene-eeo** [comment]
:+1: nice, thanks for the link.

**Comment by amjith** [comment]
I created a performance benchmark based on your snippet but I wanted to use a more drastic use case. 

```
from timeit import timeit
import random

def gen_item(m):
    return ''.join([random.choice('abcdefghijklmnopqrstuvwxyz') for _ in
        range(m)])

def gen_list(n=500, m=800):
    return [x for x in gen_item(m)]

def test_large_set():
    time = timeit('fuzzyfinder(query, collection)', setup='from __main__ import (gen_item, gen_list); from fuzzyfinder import fuzzyfinder; collection = gen_list(); query = gen_item(20)', number=50000)
    print "time:", time

test_large_set()
```

I created a branch with your code: https://github.com/amjith/fuzzyfinder/commits/no-regex-test

Cpython Performance: 18.46seconds

---

I spent a little time rewriting the code you posted above to create this: 

https://github.com/amjith/fuzzyfinder/commits/amjith/no-regex-old

I've simplified the code to not create functions but to search iteratively in a for loop. 

I found the results very disappointing.

Performance: 29.28seconds

---

Then the version from master:

Performance: 13.16seconds

---

I'm not sure what to make of this. I think the regex implementation in Python is quite efficient. I also think that a regular substring search will win when the input is small but it will quickly devolve into terribleness when the input string is large.

Thoughts?

**Comment by eugene-eeo** [comment]
yea probably that would be expected, because with more input we are spending more time in the highly optimised C code from `re`. did you try it on PyPy though? algorithmically maybe the no-regex version is better from a complexity POV but due to indirection, optimised C etc. `re` will win in practice.

**Comment by amjith** [comment]
`find()` is also an optimized C function. I think the difference is in the fact that calls to `find()` grows linearly for every character added to the input whereas the calls to the regex match is a single call regardless of the length of the input.

You're right about pypy:

```
Regex version: 0.532340049744
Your No Regex version: 0.0719439983368
My No Regex version : 0.100152015686
```
