### ISSUE TITLE
How to make the dynamic  combobox like your introduce in your project ?

### ISSUE THREAD

**Issue by OriLiMu** [amjith/fuzzyfinder#4]
I mean the combobox 
I google it and find combox but it don't like this.
![combobox ](https://raw.githubusercontent.com/amjith/fuzzyfinder/master/screenshots/pgcli-fuzzy.gif)

**Comment by amjith** [comment]
Hi. That combobox is part of [pgcli](http://pgcli.com). It's a postgres command line client written in Python. That combobox especially is created using a python library called [prompt-toolkit](https://github.com/jonathanslenders/python-prompt-toolkit).

It's a great library that makes it easy to create rich command line apps. If you're looking for a getting started guide, I'd highly recommend the [tutorial](https://github.com/jonathanslenders/python-prompt-toolkit/tree/master/examples/tutorial).

**Comment by OriLiMu** [comment]
@amjith tnx I will try ~
