### ISSUE TITLE
Fuzzy finder should be case insensitive

### ISSUE THREAD

**Issue by sudormrfbin** [amjith/fuzzyfinder#6]
Fuzzy finders are usually case insensitive. It would be nice if this one is too.

**Comment by amjith** [comment]
You're right. It will be a trivial change to add that by editing the re.compile() to include the re.IGNORECASE flag in [line 20](https://github.com/amjith/fuzzyfinder/blob/master/fuzzyfinder/main.py#L20). 

Would you be interested in sending a PR to that effect? 😄

**Comment by sudormrfbin** [comment]
Sure 😊

**Comment by amjith** [comment]
I've released a new version to PyPI. So you can install it via `pip install fuzzyfinder`. 

Do you use fuzzyfinder in any of your projects?

**Comment by sudormrfbin** [comment]
I plan to use it in one of my projects - [clid](https://github.com/gokulsoumya/clid). I'm rewriting it, and was looking for a fuzzy finder to filter filenames. And I found yours 😊

**Comment by farnja** [comment]
Any reason this shouldn't be an option? IHaveLotsOfCamelCaseThingsIWantToQuicklyFind. 😄
