### ISSUE TITLE
VSCode Doesn't recognise import

### ISSUE THREAD

**Issue by modelmat** [amjith/fuzzyfinder#9]
![image](https://user-images.githubusercontent.com/25718989/36067669-aee63dba-0f15-11e8-87a5-5f81dbb48083.png)
Yet it still works, just errors.

**Comment by gokulsoumya** [comment]
There's an`export` decorator defined in `__init.py__`:

python
```
def export(defn): """Decorator to explicitly mark functions that are exposed in a lib.""" globals()[defn.__name__] = defn __all__.append(defn.__name__) return defn
```

**Comment by modelmat** [comment]
Then why is it not defined?

**Comment by sudormrfbin** [comment]
The function _is_ defined; it's just decorated with an `export` function:

```python3
# fuzzyfinder/__init__.py

def export(defn):

"""Decorator to explicitly mark functions that are exposed in a lib."""

globals()[defn.__name__] = defn
__all__.append(defn.__name__)
return defn

```

The name `fuzzyfinder` is added to the namespace at runtime. Pylint is a static analyser. Since the namespace is modified at runtime, Pylint won't find the name`fuzzyfinder`, and will show an error.

**Comment by modelmat** [comment]
Then how can I fix, other than just to make pylint ignore the error?

**Comment by sudormrfbin** [comment]
Just use `from fuzzyfinder.main import fuzzyfinder`.
